[[news]]
date = "2026-09"
content = "An auction business protocol for AI agents communicating over A2A."
link_text = "A2A Auction Protocol"
url = "https://github.com/Runchen-Xu/a2a-auction-protocol/tree/main"

[[news]]
date = "2026-08"
content = "One paper multi-agent Webpage Generation is accepted by EMNLP 2026."

[[news]]
date = "2026-04"
before_link = "My Chrome extension "
link_text = "QuickPage Capture"
after_link = " is now available on the Chrome Web Store."
url = "https://chromewebstore.google.com/detail/quickpage-capture/afaeaifhhnjeihopkbpffabdafbfgban?pli=1"
